# Change these first
owner: MasterEvarior # Your GitHub username
repo: uptime-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: Personal Website
    url: https://giannin.dev
  - name: Aare Guru Dashboard
    url: https://aare-guru-dashboard.giannin.dev
  - name: Cocktail Menu
    url: https://masterevarior.github.io/cocktail-menu/#/

status-website:
  cname: status.giannin.dev
  logoUrl: https://avatars.githubusercontent.com/u/36074738
  name: "Giannin's Uptime Monitor"
  theme: dark
  introTitle: "Uptime monitor and status page for my website(s)"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/MasterEvarior/uptime-monitor). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: About me
      href: https://giannin.dev
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true
