owner: MasterEvarior # Your GitHub username
repo: uptime-monitor # Your GitHub repository name

# Add your sites here
sites:
  - name: Personal Website
    url: https://giannin.dev
  - name: Aare Guru Dashboard
    url: https://aare-guru-dashboard.giannin.dev
  - name: Cocktail Menu
    url: https://cocktail-menu.giannin.dev

status-website:
  cname: status.giannin.dev
  logoUrl: https://avatars.githubusercontent.com/u/36074738
  name: "Giannin's Status Page"
  theme: dark
  introTitle: "Status Page for my Website(s)"
  introMessage: "Status page for all websites under the .giannin.dev domain. Uses the excellent [Upptime project](https://upptime.js.org)."
  navbar:
    - title: Status
      href: /
    - title: About me
      href: https://giannin.dev
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
